/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-source-sans-3)", "sans-serif"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",

        // ===== PRIMARY BLUES =====
        midnightNavy: "#012453",
        deepNavy: '#0F2348',
        deepCobalt: "#0F316E",
        royalAzure: "#3B72D8",
        skyRoyal: "#3374CC",
        softBlue: "#A1C0EF",
        sky: "#D1ECF9",
        dustyBlue: '#5E8296',
        royalBlue: '#2479C9',
        royal: '#0D99FF',
        navyBlue: '#073A55',
        blueLight: '#AAD6F0',
        mistyBlue: '#BFD8FA',
        steelBlue: "#1E4170", 
        oceanBlue: "#5D99EA",
        blue: '#519CE3',
        highlight: '#B6CFF2',
        slateBlue: "#4C75AD",
        mutedSteelBlue: '#456898',
        cobaltBlue: '#476EAE',
        skyBlue: '#5D9AEA',
        paleSky: "#B3D2E3",
        tealBlue: '#48B3AF',
        iceWhite: "#F0FAFF",
        richBlue: '#2655AE',
        
        // ===== ACCENT COLORS =====
        crimsonRose: "#A74555",
        coral: "#D26363",
        dustyCoral: "#D26B7C",
        crimsonMaroon: '#7E2433',
        babyPink: "#FFC3CB",
        goldenYellow: '#F3CD55',
        oliveGold: '#8E7524',
        olive: '#886421',
        lightYellow: '#F2D092',
        golden: '#D09D4B',
        antiqueGold: "#977124",
        mutedMustard: "#C4AC5F",
        paleCream: "#FFF4DE",
        bronzeBrown: "#995C31",
        peach: "#F6C192",
        brightGreen: '#63D289',
        forestGreen: '#378451',
        emeraldGreen: "#378451",
        mintyGreen: "#70B17B",
        paleGreen: '#A7E399',
        mintGreen: "#DCFCE7",

        // ===== NEUTRALS =====
        charcoalGray: "#242D3A",
        slateGray: "#5C6879",
        steelGray: '#636B78',
        ashGray: "#808792",
        graphiteGray: "#575757",
        charcoal: '#66657C',
        coal: '#534949',
        gray: '#5E5E5E',
        graphite: '#737373',
        ash: '#9C9C9C',
        softGray: "#DDDDDD",
        soft: '#D4D4D4',
        snowWhite: "#F9F9F9",
        snow: '#F8F8F8',

        btn: {
          background: "hsl(var(--btn-background))",
          "background-hover": "hsl(var(--btn-background-hover))",
        },
      },
    },
  },
  plugins: [],
};
